version: 0.1

phases:
  pre_build:
    commands:
      - echo Build started on `date`
      - make config-env
  build:
    commands:
      - echo Building the Docker image...
      - make build
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - make push-latest
artifacts:
    files: build/out/config-env.json
    discard-paths: yes
